### ISSUE TITLE
Clan war data

### ISSUE THREAD

**Issue by richagain** [SoptikHa2/crapi-csharp-wrapper#12]
Hi, Royale api has released the data for clan war. Could you update your project?

**Comment by SoptikHa2** [comment]
I can find clan war data in neither documentation nor API response. Could you please provide some source? Thank you

**Comment by SoptikHa2** [comment]
As no source was provided and I cannot find this in official documentation and not even in API response, I'm closing this issue. Let me know if you find source. If you want this to be added to API, create [Royale API issue](https://github.com/RoyaleAPI/cr-api).
