### ISSUE TITLE
the get player and chest are separated now

### ISSUE THREAD

**Issue by richagain** [SoptikHa2/crapi-csharp-wrapper#13]
hi, 

the royale api separated the get player and chest api, can you help update?

**Comment by richagain** [comment]
I temporary added the codes in your project to get chests, but I can't submit to this git.

 public async Task<Player> GetPlayerAsync(string tag, string[] include = null, string[] exclude = null)
        {
            string query = String.Empty;
            if (include != null && exclude != null)
                throw new ArgumentException("At least one of parameters (include, exclude) must be NULL", "include, exclude");
            if (include != null)
                query += "?keys=" + String.Join(",", include);
            if (exclude != null)
                query += "?exclude=" + String.Join(",", exclude);

            Player cachedResult = cache.GetFromCache<Player>(tag + String.Join("", include ?? new string[0]) + String.Join("", exclude ?? new string[0]));
            if (cachedResult != null)
                return cachedResult;

            Task<string> output = GetAsync(Endpoints.Player, tag + query);
            

> Task<string> chest = GetAsync(Endpoints.Player, tag + "/chests");
>             PlayerChestCycle chests = Parse<PlayerChestCycle>(await chest);
>             Player result = Parse<Player>(await output);
>             result.chestCycle = chests;

            cache.Update(result, tag + String.Join("", include ?? new string[0]) + String.Join("", exclude ?? new string[0]));

            return result;
        }

**Comment by SoptikHa2** [comment]
Thank you. I've already added it to new version - which contains also new mining mode. It'll be released in few minutes.
