### ISSUE TITLE
parameter for wr.SearchForTournament should be name

### ISSUE THREAD

**Issue by richagain** [SoptikHa2/crapi-csharp-wrapper#18]
The parameter for SearchForTournament and SearchForTournamentAsync should be name, instead of tag.

**Comment by SoptikHa2** [comment]
[It already is](https://github.com/SoptikHa2/crapi-csharp-wrapper/blob/master/CR%20API%20Standart%20Wrapper/Wrapper.cs#L310). If you didn't mean parameter name, open the issue again.
