### ISSUE TITLE
Collection was modified; enumeration operation may not execute

### ISSUE THREAD

**Issue by nprocko** [SoptikHa2/crapi-csharp-wrapper#2]
I get this error when I attempt to use GetPlayer many times in a row. It seems to happen somewhere around 70-90 reliably, but not at a specific count or tag. 

I tracked the issue down to the GetPlayer call, and it looks like I'm currently able to work around it by re-instantiating the wrapper using "New" before every call I make, but I wouldn't think that should be necessary.

**Comment by SoptikHa2** [comment]
Sorry for late reply.

I was not able to replicate the bug, it was probably in older version. Please let me know if you still experience the bug. Thanks.

**Comment by nprocko** [comment]
I shifted the "new" statement back outside the loop and was able to process a couple hundred records without seeing the issue, so you're probably right that it was resolved in a newer version.
