### ISSUE TITLE
currentPlayers and maxPlayers are the same?

### ISSUE THREAD

**Issue by richagain** [SoptikHa2/crapi-csharp-wrapper#20]
Hi,

I am not sure if this is the bug from the RoyaleApi.

When I got OpenTournamentsAsync, I got the currentPlayers and maxPlayers all 50.

Please refer to the attached image.

I tried to explore in your source codes but I didn't find a clue. 

Please check it up. Maybe it is the issue from Royale API.

Thanks very much for your effort and time.

<img width="370" alt="screen shot 2018-08-16 at 10 27 16 am" src="https://user-images.githubusercontent.com/8521779/44183833-2f195100-a13f-11e8-9b80-0f80ce15153c.png">

**Comment by SoptikHa2** [comment]
I don't have access to my computer right now, this might take few days.

If you want to investigate, latest api response in json is stored in `api.ServerResponse`.

**Comment by richagain** [comment]
I have checked the source codes, but I didn't find any error. No clue so far. Maybe it was mismatched the currentPlayers with maxPlayers.

**Comment by SoptikHa2** [comment]
From quick peek it looks like API sends these numbers. I'll check API docs tomorrow, but it looks odd.

**Comment by SoptikHa2** [comment]
I no longer use this wrapper and the development stalls for several months. I'll add in into readme in few minutes, but if you still use this, I suggest you to switch over to [https://github.com/Blind-Striker/clash-royale-client-dotnet](another .Net wrapper).
