### ISSUE TITLE
More Api have been added

### ISSUE THREAD

**Issue by richagain** [SoptikHa2/crapi-csharp-wrapper#5]
Please update this wrapper.

**Comment by SoptikHa2** [comment]
Thank you. New version will be released in few days.

**Comment by SoptikHa2** [comment]
Wrapper was updated. Some endpoints like developer key stats (list of api calls/day) will be added later. I've also rewritten big part of `Wrapper.cs`. I've uploaded newest version to nuget (version 0.5.5).
