### ISSUE TITLE
wr.GetOpenTournaments() hangs

### ISSUE THREAD

**Issue by richagain** [SoptikHa2/crapi-csharp-wrapper#6]
wr.GetOpenTournaments() never returns, it hangs (loading in loop infinitely)

**Comment by richagain** [comment]
no need to use task.wait();

**Comment by richagain** [comment]
actually your wr.GetOpenTournaments() called wr.GetOpenTournamentsAsync().

if my action doesn't have await Task, I will not get the response from API.

**Comment by SoptikHa2** [comment]
I cannot replicate it. I tried it several times, I tested every endpoint (8 requests) (including multiple-players and multiple-clans requests) (including `GetOpenTournaments`) and it finished in 11 seconds.

Does it work now? Maybe there was problem with API that was fixed shortly after you reported it. Does it work when you request from API manually?

I'm closing this issue. If it still doesn't work for you and you give me more informations, I'll reopen the issue.
