### ISSUE TITLE
Simplified Clan is not what api model to be

### ISSUE THREAD

**Issue by richagain** [SoptikHa2/crapi-csharp-wrapper#8]
I wanted to getTopClansAsync, it returned SimplifiedClan, which has no rank, previous rank etc. Please look into it and fix it. Thanks so much.

**Comment by SoptikHa2** [comment]
API don't return full clan structure from top clans, clan from player's profile nor from clan search. You have to request clan profile.

`wr.GetClan(wr.GetTopClans()[0].tag);` (code is not tested, but you get the idea)
