### ISSUE TITLE
How to get player's best season rank?

### ISSUE THREAD

**Issue by richagain** [SoptikHa2/crapi-csharp-wrapper#9]
As title.

I don't know how to get.

player.leagueStatistics.bestSeason?

**Comment by SoptikHa2** [comment]
First of all get player
`Player plr = wr.GetPlayer("tag");`
Then you can simply get best season:
`plr.leagueStatistics.bestSeason;`

If you want to know more about seasons, here's everything you need to know: https://github.com/SoptikHa2/crapi-csharp-wrapper/blob/master/CR%20API%20csharp%20wrapper/Player/LeagueStatistics.cs

Both `leagueStatistics` and `bestSeason` may be null.
